### ISSUE TITLE
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument

### ISSUE THREAD

**Issue by 365gg** [ultralytics/google-images-download#5]
_DevTools listening on ws://127.0.0.1:53852/devtools/browser/bc25e6c0-e37c-4083-9092-7b062cd14cf8
Traceback (most recent call last):
  File "bing_scraper.py", line 936, in <module>
    main()
  File "bing_scraper.py", line 922, in main
    paths, errors = response.download(arguments)  # wrapping response in a variable just for consistency
  File "bing_scraper.py", line 759, in download
    paths, errors = self.download_executor(arguments)
  File "bing_scraper.py", line 871, in download_executor
    raw_html = self.download_extended_page(url, arguments['chromedriver'])
  File "bing_scraper.py", line 206, in download_extended_page
    browser.get(url)
  File "D:\Program Files\Anaconda3\envs\python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in
 get
    self.execute(Command.GET, {'url': url})
  File "D:\Program Files\Anaconda3\envs\python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in
 execute
    self.error_handler.check_response(response)
  File "D:\Program Files\Anaconda3\envs\python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242,
 in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: headless chrome=81.0.4044.129)_

I am using this command:
`python bing_scraper.py --url 'https://www.bing.com/images/search?q=parcel' --limit 100 --download --chromedriver ../chromedriver.exe`

and the version of chromedriver is  81.0.4044.129

**Comment by 365gg** [comment]
I try the command, from [https://github.com/hardikvasa/google-images-download/issues/301]()
`python bing_scraper.py --search "parcel" --limit 100 --download --chromedriver ../chromedriver.exe`
and it works well.

**Comment by glenn-jocher** [comment]
It seems like you're encountering an issue with the command `python bing_scraper.py --url 'https://www.bing.com/images/search?q=parcel' --limit 100 --download --chromedriver ../chromedriver.exe` and the specific chromedriver version 81.0.4044.129. 

Your description indicates a potential problem with the command or the compatibility of the chromedriver version. 

You might want to consider updating the chromedriver to see if that resolves the issue. Additionally, please ensure that the command is correctly formatted and any required arguments are being provided accurately.

Feel free to reach out for further assistance if needed.

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has now been merged in [PR #46: Refresh Bing scraper workflows and CI](https://github.com/ultralytics/google-images-download/pull/46) by @glenn-jocher.

The merged changes include several updates that may resolve the behavior reported here:

- improved Bing scraper reliability and URL handling
- support for direct Python `search` usage without older `keywords` requirements
- better handling of copied/pasted and quoted URLs
- preserved Bing filter parameters and improved Bing-first search behavior
- more robust downloads from extensionless image URLs using HTTP `Content-Type`
- safer handling of Unicode URLs and filenames
- optional ChromeDriver usage when Selenium can manage it automatically
- safer browser cleanup
- new automated CI and test coverage for key scraper behaviors
- updated documentation clarifying when Chrome is or isn’t needed

Credit to @glenn-jocher for the fix and to all contributors helping improve the project.

If you'd like to test whether this resolves the issue, you can install the latest `main` branch directly:

```bash
pip install git+https://github.com/ultralytics/google-images-download.git@main
```

Or, if preferred, wait for the next official PyPI release.

If possible, please try the updated code and report back on whether it resolves the issue in your environment.

Thanks 🙏 for reporting this, and any additional feedback is welcome if the issue still persists.

**Comment by glenn-jocher** [comment]
Thanks for the report. PR #46 is now merged and addresses this workflow by stripping accidental surrounding quote characters from `--url` values and avoiding Selenium for `--limit 100` or lower.

The recommended Windows command is now:

```bash
python bing_scraper.py --url "https://www.bing.com/images/search?q=parcel" --limit 100 --download
```

Remaining limitation: for more than 100 images the scraper still uses Selenium/Chrome to scroll Bing Images, so Chrome must be installed and Selenium must be able to locate a compatible driver, or you can pass `--chromedriver /path/to/chromedriver`.
